import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/globals.css";
import logo from "../assets/logo.svg";
import Image from "next/image";

const roboto = Roboto({
  weight: ["700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ignite Shop Next 14",
  description: "Generated by Rafael Neves(nevesrafael.dev@gmail.com)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-zinc-900">
      <link rel="icon" href="./favicon.svg" type="image/svg+xml" />
      <body
        className={`${roboto.className} flex flex-col items-start justify-center min-h-screen antialiased`}
      >
        <header className="py-8 w-full max-w-[1180px] mx-auto">
          <Image src={logo} alt="ignite logo" />
          {children}
        </header>
      </body>
    </html>
  );
}
